services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=pizzapalacedb'
      - 'POSTGRES_PASSWORD=NetherRealm43v3r'
      - 'POSTGRES_USER=nightmare070812'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: