# Este archivo contiene informacion en local host, informacion real no utilizada ni comiteada- obvio

server.port=8090
server.servlet.context-path=/pizzapalace/api

spring.datasource.url=jdbc:postgresql://localhost:5432/pizzapalacedb
spring.datasource.username=nightmare070812
spring.datasource.password=NetherRealm43v3r

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true